# Generated by Django 3.2.4 on 2021-07-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='state',
            field=models.CharField(default='null', max_length=30),
        ),
    ]
